<?php
require_once __DIR__ . '/config_session.php';
// --- セキュリティと初期設定 ---
session_start();
define('ABS_PANEL_INCLUDED', true);

// ログインしていない場合は処理を中断
if (!isset($_SESSION['is_logged_in']) || $_SESSION['is_logged_in'] !== true) {
    header('HTTP/1.0 403 Forbidden');
    die("Access denied.");
}

require_once __DIR__ . '/config.php';
require_once __DIR__ . '/astman.php';
require_once __DIR__ . '/functions.php';

// 文字エンコーディングをUTF-8に設定
mb_internal_encoding('UTF-8');

// --- バックアップ処理 ---

// 1. バックアップ対象のAstDBファミリーを取得(config.php)
$families_to_backup = BACKUP_FAMILIES;

// 2. ヘッダー情報を生成
$timestamp = (new DateTime('now', new DateTimeZone('Asia/Tokyo')))->format('Y-m-d H:i:s');
$backup_content = "# ABS Panel Backup File\n";
$backup_content .= "# Version: 1.0\n";
$backup_content .= "# Timestamp: {$timestamp} (JST)\n";
$backup_content .= "# --- DO NOT EDIT THIS FILE ---\n\n";

// 3. 各ファミリーのデータを取得して結合
foreach ($families_to_backup as $family) {
    // AMI経由でコマンドを実行
    $command = "database show {$family}";
    $output = AbspFunctions\exec_cli_command($command);
    
    // exec_cli_command の戻り値から、実際のDB内容だけを抽出する
    $lines = explode("\n", $output);
    $db_entries = [];
    foreach ($lines as $line) {
        // AMIメッセージに該当するものは処理しない
        if (preg_match('/Response: Success/', $line)) continue;
        else if (preg_match('/Message: Command output follows/', $line)) continue;
        else if (preg_match('/results found/', $line)) continue;
        else {
            //上記AMIのメッセージ出力に該当しなければ先頭のOuputを削除して出力用に
            $db_entries[] = str_replace('Output: ', '', $line);
        }
    }
    
    if (!empty($db_entries)) {
        $backup_content .= "# --- Family: /{$family} ---\n";
        $backup_content .= implode("\n", $db_entries) . "\n\n";
    }
}

// 4. ダウンロード用のHTTPヘッダーを送信
$filename = 'abspanel-backup-' . date('Ymd-His') . '.txt';
header('Content-Type: text/plain; charset=utf-8');
header('Content-Disposition: attachment; filename="' . $filename . '"');
header('Content-Length: ' . strlen($backup_content));
header('Expires: 0');
header('Cache-Control: must-revalidate');
header('Pragma: public');

// 5. ファイル内容を出力
echo $backup_content;
exit;
