<?php
if (!defined('ABS_PANEL_INCLUDED')) { die("Direct access is not permitted."); }

// GET時処理
$model_id = $_GET['model'] ?? '';
if ($_SERVER['REQUEST_METHOD'] === 'GET' && isset($_GET['action']) && $_GET['action'] === 'clear') {
    if ($model_id) {
        unset($_SESSION['pana_key_generator'][$model_id]);
    }
    header('Location: index.php?page=prov-pana-keys&model=' . $model_id);
    exit;
}

$config_path = __DIR__ . '/provisioning/' . $model_id . '.json';
$config = null;
if ($model_id && is_readable($config_path)) {
    $config = json_decode(file_get_contents($config_path), true);
}

// セッションから生成結果とフォーム入力を取得
$generator_data = $_SESSION['pana_key_generator'][$model_id] ?? null;
$form_values = $generator_data['form_inputs'] ?? [];

// フラッシュメッセージ
$flash_message = $_SESSION['flash_message'] ?? null;
unset($_SESSION['flash_message']);

// POST時処理
if ($_SERVER['REQUEST_METHOD'] === 'POST' && $config) {
    $flash_message = ['type' => 'success', 'text' => '処理が完了しました。'];
    $function = $_POST['function'] ?? '';

    switch ($function) {
        case 'keyset':
            $inputs = $_POST;
            $content = "# Panasonic SIP Phone Standard Format File # DO NOT CHANGE THIS LINE!\n\n";

            $keys_to_process = ['main' => $config];
            if (isset($inputs['usedss']) && $inputs['usedss'] === 'yes' && isset($config['dss'])) {
                $keys_to_process['dss'] = $config['dss'];
            }

            // 機能値のマッピングは常にルートの設定($config)から取得する
            $func_map = $config['func_values'] ?? [];

            foreach ($keys_to_process as $type => $key_config) {
                $prefix = ($type === 'dss') ? 'dss_' : 'flex_';
                $content .= "\n# {$key_config['key_type']} Keys (Generated by ABS Panel)\n";
                
                foreach(['act', 'arg', 'quick', 'label'] as $param_type) {
                    $content .= "#\n";
                    for ($i = 1; $i <= $key_config['key_count']; $i++) {
                        $param_name = $key_config['params'][$param_type];
                        $facil = $inputs["{$prefix}facil{$i}"] ?? 'none';
                        $keyarg = $inputs["{$prefix}keyarg{$i}"] ?? '';
                        $label = $inputs["{$prefix}label{$i}"] ?? '';
                        $value = '';
                        
                        if ($param_type === 'act' && isset($func_map[$facil])) {
                            $value = $func_map[$facil];
                        } elseif ($param_type === 'arg' && $facil !== 'quick') {
                            $value = $keyarg;
                        } elseif ($param_type === 'quick' && $facil === 'quick') {
                            $value = $keyarg;
                        } elseif ($param_type === 'label') {
                            $value = $label;
                        }
                        $content .= "{$param_name}{$i}=\"{$value}\"\n";
                    }
                }
            }

            $_SESSION['pana_key_generator'][$model_id] = ['content' => $content, 'form_inputs' => $inputs];
            $flash_message['text'] = '設定ファイルを生成しました。内容を確認して保存してください。';
            break;

        case 'savetofile':
             if (isset($_POST['savechecked']) && $_POST['savechecked'] === 'yes') {
                if ($generator_data) {
                    $pmodel = $_POST['phonemodel'] ?? ''; // HDVモデル選択用
                    $filename = $config['filename'] ?? ($config['filename_prefix'] . $pmodel . $config['filename_suffix']);
                    $product_file = PROV_PATH . '/' . PROV_PANA . '/' . $filename;
                    
                    if (!is_dir(dirname($product_file))) mkdir(dirname($product_file), 0755, true);
                    
                    if (file_put_contents($product_file, str_replace("\r", '', $generator_data['content'])) !== false) {
                        $flash_message['text'] = "設定ファイル({$product_file})を保存しました。";
                        unset($_SESSION['pana_key_generator'][$model_id]);
                    } else {
                        $flash_message = ['type' => 'error', 'text' => 'ファイルの保存に失敗しました。'];
                    }
                }
            } else {
                $flash_message = ['type' => 'error', 'text' => '保存するには確認チェックボックスをオンにしてください。'];
            }
            break;
    }
    if ($flash_message) { $_SESSION['flash_message'] = $flash_message; }
    header('Location: ' . $_SERVER['REQUEST_URI']);
    exit;
}

?>

<?php if (!$config): ?>
    <h2>エラー</h2>
    <p>指定された機種（<?= htmlspecialchars($model_id, ENT_QUOTES, 'UTF-8') ?>）の設定ファイルが見つかりません。</p>
<?php else: ?>
    <h2><?= htmlspecialchars($config['model_name'], ENT_QUOTES, 'UTF-8') ?> キー設定</h2>

    <?php if ($flash_message): ?>
    <div class="notice-message" style="color: <?= $flash_message['type'] === 'error' ? '#f44336' : '#4CAF50' ?>; margin-bottom: 1.5em; font-weight: bold;">
        <?= htmlspecialchars($flash_message['text'], ENT_QUOTES, 'UTF-8') ?>
    </div>
    <?php endif; ?>
    
    <form action="" method="post">
        <input type="hidden" name="function" value="keyset">
        
        <?php if ($model_id === 'kxhdv'): ?>
        <div class="form-inline-group" style="margin-bottom: 1.5em;">
            <label for="phonemodel">対象機種:</label>
            <select id="phonemodel" name="phonemodel">
                <option value="230" <?= (($form_values['phonemodel'] ?? '') === 'hdv230') ? 'selected' : '' ?>>KX-HDV230N</option>
                <option value="330" <?= (($form_values['phonemodel'] ?? 'hdv330') === 'hdv330') ? 'selected' : '' ?>>KX-HDV330N</option>
                <option value="430" <?= (($form_values['phonemodel'] ?? '') === 'hdv430') ? 'selected' : '' ?>>KX-HDV430N</option>
            </select>
        </div>
        <?php endif; ?>
        
        <h3><?= $config['key_type'] ?>キー設定</h3>
        <div class="table-container">
            <table class="absp-table">
                <thead>
                    <tr>
                        <th>キー番号</th><th>ラベル</th><th>機能</th><th>値</th>
                        <th style="width: 2em; background-color: var(--bg-color);"></th>
                        <th>キー番号</th><th>ラベル</th><th>機能</th><th>値</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    $key_count = $config['key_count'];
                    $rows = ceil($key_count / 2);
                    for ($i = 1; $i <= $rows; $i++):
                        $key_left = ($config['layout']['key_order_desc'] ?? false) ? ($rows - $i + 1) : $i;
                        $key_right = $key_left + $rows;
                    ?>
                    <tr>
                        <td><?= $config['key_type'] . $key_left ?></td>
                        <td><input type="text" name="flex_label<?= $key_left ?>" class="input-short2" value="<?= htmlspecialchars($form_values["flex_label{$key_left}"] ?? '', ENT_QUOTES, 'UTF-8') ?>"></td>
                        <td>
                            <select name="flex_facil<?= $key_left ?>">
                                <?php foreach ($config['functions'] as $val => $text): ?>
                                    <option value="<?= $val ?>" <?= (($form_values["flex_facil{$key_left}"] ?? 'none') == $val) ? 'selected' : '' ?>><?= $text ?></option>
                                <?php endforeach; ?>
                            </select>
                        </td>
                        <td><input type="text" name="flex_keyarg<?= $key_left ?>" class="input-short2" value="<?= htmlspecialchars($form_values["flex_keyarg{$key_left}"] ?? '', ENT_QUOTES, 'UTF-8') ?>"></td>
                        <td style="background-color: var(--bg-color);"></td>
                        <td><?= $config['key_type'] . $key_right ?></td>
                        <td><input type="text" name="flex_label<?= $key_right ?>" class="input-short2" value="<?= htmlspecialchars($form_values["flex_label{$key_right}"] ?? '', ENT_QUOTES, 'UTF-8') ?>"></td>
                        <td>
                            <select name="flex_facil<?= $key_right ?>">
                                <?php foreach ($config['functions'] as $val => $text): ?>
                                    <option value="<?= $val ?>" <?= (($form_values["flex_facil{$key_right}"] ?? 'none') == $val) ? 'selected' : '' ?>><?= $text ?></option>
                                <?php endforeach; ?>
                            </select>
                        </td>
                        <td><input type="text" name="flex_keyarg<?= $key_right ?>" class="input-short2" value="<?= htmlspecialchars($form_values["flex_keyarg{$key_right}"] ?? '', ENT_QUOTES, 'UTF-8') ?>"></td>
                    </tr>
                    <?php endfor; ?>
                </tbody>
            </table>
        </div>
        
        <?php if (isset($config['dss'])): // DSS設定があるモデルの場合 ?>
        <h3 style="margin-top: 2em;"><?= $config['dss']['key_type'] ?>キー設定 (KX-HDV20)</h3>
        <div class="form-inline-group" style="margin-bottom: 1em;">
            <input type="checkbox" id="usedss" name="usedss" value="yes" <?= isset($form_values['usedss']) ? 'checked' : '' ?>>
            <label for="usedss">DSSコンソールを使用する</label>
        </div>
        <div class="table-container">
             <table class="absp-table">
                <thead>
                    <tr><th>キー番号</th><th>ラベル</th><th>機能</th><th>値</th><th style="width: 2em; background-color: var(--bg-color);"></th><th>キー番号</th><th>ラベル</th><th>機能</th><th>値</th></tr>
                </thead>
                <tbody>
                    <?php
                    $dss_key_count = $config['dss']['key_count'];
                    $dss_rows = ceil($dss_key_count / 2);
                    for ($i = 1; $i <= $dss_rows; $i++):
                        $key_left = ($config['dss']['layout']['key_order_desc'] ?? false) ? ($dss_rows - $i + 1) : $i;
                        $key_right = $key_left + $dss_rows;
                    ?>
                     <tr>
                        <td><?= $config['dss']['key_type'] . $key_left ?></td>
                        <td><input type="text" name="dss_label<?= $key_left ?>" class="input-short2" value="<?= htmlspecialchars($form_values["dss_label{$key_left}"] ?? '', ENT_QUOTES, 'UTF-8') ?>"></td>
                        <td>
                            <select name="dss_facil<?= $key_left ?>">
                                <?php foreach ($config['functions'] as $val => $text): ?><option value="<?= $val ?>" <?= (($form_values["dss_facil{$key_left}"] ?? 'none') == $val) ? 'selected' : '' ?>><?= $text ?></option><?php endforeach; ?>
                            </select>
                        </td>
                        <td><input type="text" name="dss_keyarg<?= $key_left ?>" class="input-short2" value="<?= htmlspecialchars($form_values["dss_keyarg{$key_left}"] ?? '', ENT_QUOTES, 'UTF-8') ?>"></td>
                        <td style="background-color: var(--bg-color);"></td>
                        <td><?= $config['dss']['key_type'] . $key_right ?></td>
                        <td><input type="text" name="dss_label<?= $key_right ?>" class="input-short2" value="<?= htmlspecialchars($form_values["dss_label{$key_right}"] ?? '', ENT_QUOTES, 'UTF-8') ?>"></td>
                        <td>
                            <select name="dss_facil<?= $key_right ?>">
                                <?php foreach ($config['functions'] as $val => $text): ?><option value="<?= $val ?>" <?= (($form_values["dss_facil{$key_right}"] ?? 'none') == $val) ? 'selected' : '' ?>><?= $text ?></option><?php endforeach; ?>
                            </select>
                        </td>
                        <td><input type="text" name="dss_keyarg<?= $key_right ?>" class="input-short2" value="<?= htmlspecialchars($form_values["dss_keyarg{$key_right}"] ?? '', ENT_QUOTES, 'UTF-8') ?>"></td>
                    </tr>
                    <?php endfor; ?>
                </tbody>
             </table>
        </div>
        <?php endif; ?>

        <div style="margin-top: 1em;">
            <button type="submit" class="btn btn-primary">生成実行</button>
            <a href="index.php?page=prov-pana-keys&model=<?= $model_id ?>&action=clear" class="btn">フォームをクリア</a>
        </div>
    </form>
    
    <?php if ($generator_data): ?>
        <h3 style="margin-top: 2em;">生成結果の確認と保存</h3>
        <form action="" method="post">
            <input type="hidden" name="function" value="savetofile">
            <input type="hidden" name="phonemodel" value="<?= htmlspecialchars($generator_data['form_inputs']['phonemodel'] ?? '', ENT_QUOTES, 'UTF-8') ?>">
            <textarea readonly style="width: 100%; height: 250px;"><?= htmlspecialchars($generator_data['content'], ENT_QUOTES, 'UTF-8') ?></textarea>
            <div class="form-inline-group" style="margin-top: 1em;">
                <input type="checkbox" id="savechecked" name="savechecked" value="yes">
                <label for="savechecked">内容を確認しました。ファイルを保存します。</label>
                <button type="submit" class="btn">保存する</button>
            </div>
        </form>
    <?php endif; ?>

<?php endif; ?>
