;ピックアップ機能

;ピックアップ
[dopickup]
exten => s,1,NoOp(pickup)
;自内線情報取得
exten => s,n,Gosub(sub-whoami,s,1)
;自グループ番号取得
exten => s,n,Set(MGRP=${DB(ABS/EXT/${ME}/PGRP)})
exten => s,n(direct),GotoIf($["${MGRP}"!=""]?gop)
;自グループ番号が取得できない場合フリーアドレスのケースをチェック
exten => s,n,Set(MGRP=${DB(ABS/FAP/UID/${ME}/PGRP)})
exten => s,n,GotoIf($["${MGRP}"!=""]?gop)
;それでもなければ終了
exten => s,n,Hangup
;ピックアップ対象内線取得
exten => s,n(gop),Set(TGEXT=${DB(ABS/PGRP/${MGRP})})
exten => s,n,GotoIf($["${TGEXT}"=""]?nogo)
;内線番号からエンドポイントを求めピックアップリスト組み立て
exten => s,n,Set(i=1)
exten => s,n,While($[${i}<33])
exten => s,n,Set(EXT=${CUT(TGEXT,\,,${i})})
exten => s,n,GotoIf($["${EXT}"=""]?dpick)
exten => s,n,Gosub(sub-ext2endpoint,s,1)
;ABS内部エンドポイント名だけ取り出し
exten => s,n,NoOp(${sENDPOINT})
exten => s,n,GotoIf($["${sENDPOINT}"=""]?cont)
exten => s,n,Set(PLIST=${PLIST}&${sENDPOINT})
exten => s,n(cont),Set(i=$[${i} +1])
exten => s,n,EndWhile
;実行しない場合
exten => s,n(nogo),Congestion

;ピックアップ実行
exten => s,n(dpick),Set(PLIST=${PLIST:1})
exten => s,n,PickUpChan(${PLIST},p)
exten => s,n,Congestion
