[global]
type = global
user_agent = "ABS-IP-PBX"

[system]
type=system
disable_rport = yes

[transport-udp]
type = transport
protocol = udp
bind = 0.0.0.0:5070
local_net = 192.168.0.0/16

#tryinclude "pjsip_base_acl.conf"

#tryinclude "pjsip_wsstransport.conf"

;WebUIが生成したトランクファイル読み込み
#tryinclude "/var/www/abs/trunks/pjsip_trunk_*.conf"

;試験用に電話機を疑似トランクとする場合
;本番環境には組み込まないこと
#tryinclude "pjsip_demophone.conf"

;拠点間接続用
;#include "pjsip_trunk_intra_me.conf"
;#include "pjsip_trunk_intra_ikebukuro.conf"
;#include "pjsip_trunk_intra_itabashi.conf"

