[ws-ext-2001]
type = websocket_client
uri = ws://127.0.0.1:8765
protocols = media
connection_type = per_call_config
connection_timeout = 500
reconnect_interval = 500
reconnect_attempts = 5
tls_enabled = no

[ws-ext-2002]
type = websocket_client
uri = ws://127.0.0.1:8765
protocols = media
connection_type = per_call_config
connection_timeout = 500
reconnect_interval = 500
reconnect_attempts = 5
tls_enabled = no
